@echo off
echo Menyiapkan Server Lokal...
echo (Jika muncul permintaan izin dari Firewall, silakan klik Allow/Izinkan)
echo.
echo Sedang memulai server di background...
start /b npx -y http-server -p 8080
echo Menunggu server siap (3 detik)...
timeout /t 3 >nul
echo Membuka browser...
start http://localhost:8080
echo.
echo Server sedang berjalan! 
echo JANGAN TUTUP jendela hitam ini selama Anda menggunakan aplikasi.
echo Tekan tombol apa saja untuk mematikan server...
pause >nul
